from pydantic import BaseModel, Field


class ValidationIssue(BaseModel):
    location: list[str | int] = Field(
        description="Request field location reported from the outermost object inward."
    )
    message: str
    type: str


class ErrorDetail(BaseModel):
    code: str = Field(examples=["recipe_not_found", "invalid_identifier", "validation_error"])
    message: str
    issues: list[ValidationIssue] = Field(default_factory=list)
    correlation_id: str = Field(
        min_length=36,
        max_length=36,
        pattern=r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
        description="Opaque request-scoped identifier generated by Recipe Lab.",
    )


class ErrorResponse(BaseModel):
    error: ErrorDetail
